module.exports = {
    "login": "jonny1811",
    "id": 26287713,
    "node_id": "MDQ6VXNlcjI2Mjg3NzEz",
    "avatar_url": "https://avatars3.githubusercontent.com/u/26287713?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/jonny1811",
    "html_url": "https://github.com/jonny1811",
    "followers_url": "https://api.github.com/users/jonny1811/followers",
    "following_url": "https://api.github.com/users/jonny1811/following{/other_user}",
    "gists_url": "https://api.github.com/users/jonny1811/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/jonny1811/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/jonny1811/subscriptions",
    "organizations_url": "https://api.github.com/users/jonny1811/orgs",
    "repos_url": "https://api.github.com/users/jonny1811/repos",
    "events_url": "https://api.github.com/users/jonny1811/events{/privacy}",
    "received_events_url": "https://api.github.com/users/jonny1811/received_events",
    "type": "User",
    "site_admin": false,
    "name": "jonnyda1811",
    "company": "TIPS S.A.",
    "blog": "",
    "location": "Hernandarias, Paraguay",
    "email": null,
    "hireable": true,
    "bio": "Passionate about new technologies, javascript fond of typescript.",
    "twitter_username": null,
    "public_repos": 16,
    "public_gists": 1,
    "followers": 0,
    "following": 1,
    "created_at": "2017-03-08T22:24:53Z",
    "updated_at": "2020-09-25T02:52:02Z"  
};